#pragma config(Motor,  port2,           Servo1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true) {
motor[Servo1] = 90;
wait1Msec(1);
motor[Servo1] = -180;
//	Servo1. = 127;
//setMotor(port2, 100);
//servo1.setMotorSpeeds = 127;
//Servo1 = 5;
wait1Msec(1);

}
}
