#pragma config(Motor,  port2,           largeLeft,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           largeRight,    tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



//vexRT[Ch1];

while (true) {
int forwardPower = vexRT[Ch3];
int previousChannel3 = 0;
int previousChannel4 = 0;
if (vexRT[Btn8D] == 1 ) {
motor[largeLeft] = 100;
motor[largeRight] = 112;

//motor[largeLeft] = vexRT[Ch3];
//motor[largeRight] = vexRT[Ch3];

}
//motor[largeLeft] = vexRT[Ch3]+254 * -1;
//motor[largeRight] = vexRT[Ch3]/127+254 * -1;

if (vexRT[Btn8U] == 1) {
motor[largeLeft] = -100;
motor[largeRight] = -115;
}
///
//
 if (vexRT[3] < 1) {
   //negative
} else {
//positive
}
//if (abs (vexRT[Ch3]) > 1){
if (abs(vexRT[Ch3]) > abs(vexRT[Ch4])) {
motor[largeLeft] = vexRT[Ch3];
motor[largeRight] = vexRT[Ch3];

} else {
//}

if ((vexRT[Ch4]) > 25) {
//motor[largeLeft] = vexRT[Ch4] * -1;
motor[largeLeft] = vexRT[Ch4];
motor[largeRight] = vexRT[Ch4] * 0.2;
}

if ((vexRT[Ch4]) < -25) {
//motor[largeLeft] = vexRT[Ch4] * -1;
motor[largeRight] = vexRT[Ch4] * -1;
motor[largeLeft] = vexRT[Ch4] * -0.2;

}
}
previousChannel3 = vexRT[Ch3];
previousChannel4 = vexRT[Ch4];

if (vexRT[Btn7L] == 1) {
motor[largeLeft] = 50;
motor[largeRight] = -50;

}

if (vexRT[Btn7R] == 1 ) {
motor[largeLeft] = -50;
motor[largeRight] = 50;
}

if (vexRT[Btn8L] == 1) {
motor[largeLeft] = -75;
motor[largeRight] = -100;

}

if (vexRT[Btn8R] == 1 ) {
motor[largeLeft] = -100;
motor[largeRight] = -50;
}

if (vexRT[Btn7U] == 1) {

motor[largeLeft] = 0;
motor[largeRight] = 0;



}

}
}
