#pragma config(Motor,  port2,           largeLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           largeRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

vexRT[Ch1];

while (true) {

if (vexRT[Btn8D] == 1 ) {
motor[largeLeft] = 100;
motor[largeRight] = 100;
sleep(1);
motor[largeLeft] = 300;
motor[largeRight] = 300;

}

if (vexRT[Btn8U] == 1) {
motor[largeLeft] = -100;
motor[largeRight] = -100;
sleep(1);
motor[largeLeft] = -300;
motor[largeRight] = -300;
}

if (vexRT[Btn8L] == 1) {
motor[largeLeft] = 50;
motor[largeRight] = -50;

}

if (vexRT[Btn8R] == 1 ) {
motor[largeLeft] = -50;
motor[largeRight] = 50;
}

if (vexRT[Btn7L] == 1) {
motor[largeLeft] = -50;
motor[largeRight] = -100;

}

if (vexRT[Btn7R] == 1 ) {
motor[largeLeft] = -100;
motor[largeRight] = -50;
}

if (vexRT[Btn7U] == 1) {

motor[largeLeft] = 0;
motor[largeRight] = 0;

}

}
}
