#pragma config(Motor,  port2,           largeLeft,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           largeRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1) {

motor[largeLeft] = 300;
motor[largeRight] = 20;


}
}
