#pragma config(Motor,  port3,           motor1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[port3] = 127;

}
